### PR TITLE
Update dialog_data.js

### PR DESCRIPTION
**Pull request by S-Kris-S**
Fixed minor errors in character names

### CODE REVIEW

**Comment by breakid** [comment]
I'm kind of amazed anyone actually found and was interested in this. Good catch on Disarray's name being spelled wrong.

**Comment by gusvogel** [comment]
are you actively working on a remake? i'm doing a remake of spybotics too, but in unity. https://youtu.be/dNMpnnjZngE

**Comment by breakid** [comment]
> are you actively working on a remake? i'm doing a remake of spybotics too, but in unity. https://youtu.be/dNMpnnjZngE

No. This was the product of a week-long coding session during a (2015?) vacation that I eventually got around to posting here. A few times a year I remember it and think about finishing up the last things on my to-do list, but other things always seem to take precedence.

Your remake looks awesome, way better than mine! I'd love to play it when it's ready. I don't know Unity, and I'm not very active on Discord, but I joined your server and am happy to help out if I can.

**Comment by gusvogel** [comment]
Thanks for the reply! I've spent much much longer than a week on this so that is understandable. I too have had this idea to remake it for many years on and off. thanks for joining Ill continue my chats there.

**Pull request merged**
